2025-06-27 22:03:11,194 INFO    MainThread:97155 [wandb_setup.py:_flush():81] Current SDK version is 0.20.1
2025-06-27 22:03:11,194 INFO    MainThread:97155 [wandb_setup.py:_flush():81] Configure stats pid to 97155
2025-06-27 22:03:11,194 INFO    MainThread:97155 [wandb_setup.py:_flush():81] Loading settings from /Users/charon/.config/wandb/settings
2025-06-27 22:03:11,194 INFO    MainThread:97155 [wandb_setup.py:_flush():81] Loading settings from /Users/charon/Documents/GitHub/CS336/wandb/settings
2025-06-27 22:03:11,194 INFO    MainThread:97155 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-06-27 22:03:11,194 INFO    MainThread:97155 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /Users/charon/Documents/GitHub/CS336/wandb/run-20250627_220311-3hpeit0g/logs/debug.log
2025-06-27 22:03:11,194 INFO    MainThread:97155 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /Users/charon/Documents/GitHub/CS336/wandb/run-20250627_220311-3hpeit0g/logs/debug-internal.log
2025-06-27 22:03:11,194 INFO    MainThread:97155 [wandb_init.py:init():831] calling init triggers
2025-06-27 22:03:11,194 INFO    MainThread:97155 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-06-27 22:03:11,194 INFO    MainThread:97155 [wandb_init.py:init():872] starting backend
2025-06-27 22:03:11,421 INFO    MainThread:97155 [wandb_init.py:init():875] sending inform_init request
2025-06-27 22:03:11,446 INFO    MainThread:97155 [wandb_init.py:init():883] backend started and connected
2025-06-27 22:03:11,448 INFO    MainThread:97155 [wandb_init.py:init():956] updated telemetry
2025-06-27 22:03:11,476 INFO    MainThread:97155 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-06-27 22:03:12,456 INFO    MainThread:97155 [wandb_init.py:init():1032] starting run threads in backend
2025-06-27 22:03:12,673 INFO    MainThread:97155 [wandb_run.py:_console_start():2453] atexit reg
2025-06-27 22:03:12,674 INFO    MainThread:97155 [wandb_run.py:_redirect():2301] redirect: wrap_raw
2025-06-27 22:03:12,674 INFO    MainThread:97155 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-06-27 22:03:12,674 INFO    MainThread:97155 [wandb_run.py:_redirect():2393] Redirects installed.
2025-06-27 22:03:12,677 INFO    MainThread:97155 [wandb_init.py:init():1078] run started, returning control to user process
2025-06-27 22:10:41,844 INFO    MsgRouterThr:97155 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-06-27 22:10:44,117 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,122 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,122 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,123 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,123 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,123 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,123 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,124 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,124 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,124 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,124 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,124 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,125 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,125 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,125 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,125 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,126 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,127 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,127 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,127 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,127 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,127 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,127 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,128 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,128 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,128 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,128 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,128 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,128 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,128 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-27 22:10:44,128 ERROR   MainThread:97155 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/charon/miniconda3/envs/llm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
